server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true #是否注册到eureka,默认为true
    fetch-registry: true #表示是否抓取eureka已注册的信息,如果想使用ribbon必须为true
# 设置openfeign超时时间
ribbon:
  #连接超时时间
  ReadTimeout: 7000
  #访问服务超时时间
  ConnectTimeout: 7000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignApi: debug
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值 介于0 - 1之间,1表示全部采集
      probability: 1
  application:
    name: order-service