server:
  port: 8001
spring:
  application:
    name: payment-hystrix-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #注册的eureka地址
    register-with-eureka: true #是否注册到eureka,默认为true
    fetch-registry: true #表示是否抓取eureka已注册的信息,如果想使用ribbon必须为true
  instance:
    instance-id: payment8001 #显示的节点名
    prefer-ip-address: true  #访问路径可以显示地址
    #lease-renewal-interval-in-seconds: 1 #向注册中心发送心跳的时间间隔,单位为秒(默认30秒)
    #lease-expiration-duration-in-seconds: 2 #服务端接收最后一次心跳后等待时间上限,单位为秒(默认90秒)
