server:
  port: 7001

#eurekaServer 配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false #表示不去检索服务
    register-with-eureka: false #不注册自己
    service-url:
      #注册其他节点
      #defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护机制
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000
