server:
  port: 8002
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: root

#mybatis整合boot
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    register-with-eureka: true #是否注册到eureka,默认为true
    fetch-registry: true #表示是否抓取eureka已注册的信息,如果想使用ribbon必须为true
  instance:
    instance-id: payment8002 #显示的节点名
    prefer-ip-address: true  #访问路径可以显示地址