server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true #是否注册到eureka,默认为true
    fetch-registry: true #表示是否抓取eureka已注册的信息,如果想使用ribbon必须为true
# 设置openfeign超时时间
#ribbon:
#  #连接超时时间
#  ReadTimeout: 7000
#  #访问服务超时时间
#  ConnectTimeout: 7000
#logging:
#  level:
#    com.atguigu.springcloud.service.PaymentFeignApi: debug

#开启feign都熔断机制
feign:
  hystrix:
    enabled: true
