server:
  port: 8005
spring:
  application:
    name: payment-com.atguigu.springcloud.service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}